Algoritmo "ParOuImpar"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2022
Var
   // Seção de Declarações das variáveis
   N: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   EscrevaL ("Digite um número qualquer:")
   Leia (N)
Se (N % 2 = 0) entao
EscrevaL (N, " é um número PAR!")
senao
EscrevaL (N, " é um número IMPAR!")
Fimse







Fimalgoritmo