Algoritmo "Média"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
n1 , n2, M: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite um número")
Leia (n1)
Escreval ("Digite outro número")
Leia (n2)
M <- (n1  + n2)/2
Escreval ("A média dos números é igual a ", M,".")


Fimalgoritmo