Algoritmo "Nome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2022
Var
// Seção de Declarações das variáveis 
Nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Qual é o seu nome?")
Leia (Nome)
Escreval ("Olá ", Nome ,", é um prazer te conhecer!")

Fimalgoritmo