Algoritmo "20"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/05/2022
Var
// Seção de Declarações das variáveis 
numero, teste: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite um número:")
leia (numero)
teste <- (numero%2)
Se (numero%2 = 0) entao
escreval ("O numero digitado é par.")
senao
escreval ("O número digitado é impar.")
fimse

Fimalgoritmo