Algoritmo "4"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/04/2022
Var
// Seção de Declarações das variáveis 

n1 , n2, S: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um valor:")
Leia (n1)
Escreval("Digite outro valor:")
Leia (n2)
S <- n1 + n2
Escreval ("A soma entre", n1 ," e", n2 ," é igual a" , S.)

Fimalgoritmo