Algoritmo "5"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/04/2022
Var
// Seção de Declarações das variáveis 
n1 , n2 , M: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Nota 1:")
Leia (n1)
Escreval ("Nota 2:")
Leia (n2)
M <- (n1+n2)/2
Escreval("A média entre", n1 ," e ", n2 ," é igual a" , M)

Fimalgoritmo