Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2022
Var
// Seção de Declarações das variáveis 
N:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

EscrevaL ("Digite um número:")
Leia (N)
EscrevaL ("O sucessor é " ,N+1, " e o antecessor é " ,N-1, " !")








Fimalgoritmo