Algoritmo "7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/05/2022
Var
// Seção de Declarações das variáveis 
N: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

EscrevaL ("Digite um número:")
Leia (N)
EscrevaL ("O dobro de" ,N, " é",N*2,".")
EscrevaL ("A terça parte de" ,N, " é",N/3,".")







Fimalgoritmo